name: san_choice_app
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_tts: ^4.0.2  
  shared_preferences: ^2.2.2  
  google_fonts: ^6.2.1
  flutter_launcher_icons: "^0.13.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/data/
    - assets/images/  # <-- この一行を追加（フォルダごと指定できます）

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  # macOSでも出すなら
  macos:
    generate: true